#!/bin/bash

# Check if it is running
pgrep ot-recorder
exitcode=$?
if [[ $exitcode != 0 ]]; then
	# Restart if not
	mkdir /var/spool/owntracks/recorder/htdocs
	ot-recorder --initialize
	systemctl restart ot-recorder
	sleep 10
fi
	done
fi
