#!/bin/bash

# Check if it is running
pgrep ot-recorder
exitcode=$?
if [[ $exitcode != 0 ]]; then
	# Restart if not
	service ot-recorder --initialize
	service systemctl restart ot-recorder
	sleep 10
fi
	done
fi
