#!/bin/sh

# Check whether OwnTracks Recorder is running.
if ! /usr/bin/pgrep -x ot-recorder >/dev/null 2>&1; then
    /bin/mkdir -p /var/spool/owntracks/recorder/htdocs
    /usr/sbin/ot-recorder --initialize
    /bin/systemctl restart ot-recorder
    /bin/sleep 10
fi

exit 0